services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: commerce-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www:cached
      - storage_volume:/var/www/storage
      - public_storage_volume:/var/www/public/storage
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    dns:
      - 8.8.8.8
      - 1.1.1.1
    cpus: 1.5
    mem_limit: 1.5g
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: commerce-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www:cached
      - public_storage_volume:/var/www/public/storage
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    cpus: 0.4
    mem_limit: 256m
    networks:
      - laravel

  db:
    image: postgres:16
    container_name: commerce-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    cpus: 0.8
    mem_limit: 1g
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: commerce-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3
    cpus: 0.3
    mem_limit: 256m
    networks:
      - laravel

volumes:
  pgdata:
  redisdata:
  storage_volume:
  public_storage_volume:

networks:
  laravel:
    driver: bridge
